# Generated by Django 5.0.6 on 2024-06-06 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Lección', 'Lección'), ('Tema', 'Tema'), ('Curso', 'Curso'), ('Diagnóstica', 'Diagnóstica'), ('Libre', 'Libre')], default='Libre', max_length=11)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('intentos_permitidos', models.PositiveIntegerField()),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criterios_aprobacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('banco_de_preguntas', models.JSONField(blank=True, null=True)),
                ('competencias_evaluadas', models.JSONField(blank=True, null=True)),
                ('tiempo_limite', models.PositiveIntegerField(blank=True, help_text='Tiempo límite en minutos', null=True)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('Simple', 'Simple'), ('Múltiple', 'Múltiple'), ('Abierta', 'Abierta'), ('Verdadero/Falso', 'Verdadero/Falso')], default='Simple', max_length=15)),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Moderado', 'Moderado'), ('Difícil', 'Difícil')], max_length=12)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, null=True)),
                ('explicacion_respuesta', models.TextField(blank=True)),
                ('imagen_relacionada_url', models.URLField(blank=True, max_length=1024)),
                ('audio_relacionado_url', models.URLField(blank=True, max_length=1024)),
                ('video_relacionado_url', models.URLField(blank=True, max_length=1024)),
                ('condicionales', models.JSONField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_evaluacion', to='Evaluaciones.evaluacion')),
                ('tags', models.ManyToManyField(blank=True, related_name='preguntas', to='Evaluaciones.tag')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones', to='Evaluaciones.pregunta'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Evaluaciones.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'unique_together': {('pregunta', 'texto_opcion')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.JSONField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Evaluaciones.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta a Pregunta',
                'verbose_name_plural': 'Respuestas a Preguntas',
                'unique_together': {('pregunta', 'usuario')},
            },
        ),
    ]
