# Generated by Django 5.0.6 on 2024-07-25 19:20

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoMatematico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EST', 'Estadística'), ('GEO', 'Geometría'), ('ALG', 'Álgebra y cálculo')], max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('es_generico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intentos', models.PositiveIntegerField(default=0)),
                ('puntaje_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_promedio', models.DurationField(blank=True, null=True)),
                ('tasa_aprobacion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Estadísticas de Evaluación',
                'verbose_name_plural': 'Estadísticas de Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('respuestas', models.JSONField(default=dict)),
                ('completado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Intento de Evaluación',
                'verbose_name_plural': 'Intentos de Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos', models.DecimalField(decimal_places=2, default=0, help_text='Puntos ganados si esta opción es seleccionada correctamente', max_digits=5)),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('tipo_pregunta', models.CharField(choices=[('Simple', 'Simple'), ('Múltiple', 'Múltiple'), ('Abierta', 'Abierta'), ('Verdadero/Falso', 'Verdadero/Falso')], default='Simple', max_length=15)),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Moderado', 'Moderado'), ('Difícil', 'Difícil')], max_length=12)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('imagen_svg', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('marcar_respuesta', models.BooleanField(default=False)),
                ('explicacion_respuesta', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True)),
                ('situacion', models.CharField(choices=[('Familiar', 'Familiar o personal'), ('Laboral', 'Laboral u ocupacional'), ('Comunitario', 'Comunitario o social'), ('Matemático', 'Matemático o científico')], default='Familiar', max_length=15)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta a Pregunta',
                'verbose_name_plural': 'Respuestas a Preguntas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resultado de Evaluación',
                'verbose_name_plural': 'Resultados de Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Lección', 'Lección'), ('Tema', 'Tema'), ('Curso', 'Curso'), ('Diagnóstica', 'Diagnóstica'), ('Libre', 'Libre'), ('Saber 11', 'Saber 11')], default='Libre', max_length=11)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('intentos_permitidos', models.PositiveIntegerField(default=1)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criterios_aprobacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_limite', models.PositiveIntegerField(blank=True, help_text='Tiempo límite en minutos', null=True)),
                ('resultados_visibles', models.BooleanField(default=False, help_text='Permite mostrar u ocultar los resultados a los estudiantes')),
                ('mostrar_resultados', models.BooleanField(default=False, help_text='Permite mostrar u ocultar los resultados a los estudiantes')),
                ('mostrar_opciones_correctas', models.BooleanField(default=False, help_text='Permite mostrar u ocultar las opciones correctas a los estudiantes')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rubrica', models.TextField(blank=True)),
                ('curso_evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cursos.curso')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
