# Generated by Django 5.0.6 on 2024-07-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0002_initial'),
        ('Evaluaciones', '0001_initial'),
        ('Lecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='leccion_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lecciones.leccion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tema_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cursos.tema'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones_permitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadisticasevaluacion',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='Evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intento_evaluacion', to='Evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intento_evaluacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='competencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='Evaluaciones.competencia'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='contenido_matematico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='Evaluaciones.contenidomatematico'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones', to='Evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta', to='Evaluaciones.intentoevaluacion'),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.opcion'),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='Evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='intentos',
            field=models.ManyToManyField(related_name='resultado', to='Evaluaciones.intentoevaluacion'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='mejor_intento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mejor_resultado', to='Evaluaciones.intentoevaluacion'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='Evaluaciones.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestapregunta',
            unique_together={('pregunta', 'usuario', 'intento')},
        ),
    ]
