# Generated by Django 5.0.6 on 2024-07-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoevaluacion',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='iniciado', max_length=10),
        ),
    ]
