# Generated by Django 5.0.6 on 2024-06-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0002_alter_pregunta_options_alter_opcion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opciones_pregunta', to='Evaluaciones.pregunta'),
            preserve_default=False,
        ),
    ]
