# Generated by Django 5.0.6 on 2024-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0003_intentoevaluacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='texto_pregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto_pregunta_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_svg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
