# Generated by Django 5.0.6 on 2024-07-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0004_remove_pregunta_texto_pregunta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='texto_pregunta_html',
            new_name='texto_pregunta',
        ),
    ]
