# Generated by Django 5.0.6 on 2024-07-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0005_rename_texto_pregunta_html_pregunta_texto_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_limite',
            field=models.PositiveIntegerField(help_text='Tiempo límite en minutos', null=True),
        ),
    ]
