# Generated by Django 5.0.6 on 2024-06-17 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0005_alter_intentoevaluacion_evaluacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones_permitidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
