# Generated by Django 5.0.6 on 2024-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0006_alter_evaluacion_tiempo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_svg',
            field=models.FileField(blank=True, null=True, upload_to='preguntas/imagenes/'),
        ),
    ]
