# Generated by Django 5.0.6 on 2024-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0006_evaluacion_usuarios_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoevaluacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
