# Generated by Django 5.0.6 on 2024-06-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0007_intentoevaluacion_fecha_fin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuestapregunta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='intento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Evaluaciones.intentoevaluacion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='respuestapregunta',
            unique_together={('pregunta', 'usuario', 'intento')},
        ),
    ]
