# Generated by Django 5.0.6 on 2024-07-28 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0007_alter_pregunta_imagen_svg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intentoevaluacion',
            index=models.Index(fields=['evaluacion', 'usuario', 'completado'], name='Evaluacione_evaluac_d2479d_idx'),
        ),
    ]
