# Generated by Django 5.0.6 on 2024-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0008_alter_respuestapregunta_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
    ]
