# Generated by Django 5.0.6 on 2024-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0009_pregunta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='imagen_svg',
            field=models.FileField(blank=True, null=True, upload_to='preguntas/', verbose_name='Imagen SVG'),
        ),
    ]
