# Generated by Django 5.0.6 on 2024-06-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0010_pregunta_imagen_svg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentoevaluacion',
            options={},
        ),
    ]
