# Generated by Django 5.0.6 on 2024-06-18 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0011_alter_intentoevaluacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentoevaluacion',
            options={'verbose_name': 'Intento de Evaluación', 'verbose_name_plural': 'Intentos de Evaluaciones'},
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='tiempo_tomado',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
