# Generated by Django 5.0.6 on 2024-06-18 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0012_alter_intentoevaluacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intentoevaluacion',
            name='fecha_intento',
        ),
        migrations.RemoveField(
            model_name='intentoevaluacion',
            name='tiempo_tomado',
        ),
        migrations.AlterField(
            model_name='intentoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Evaluaciones.evaluacion'),
        ),
        migrations.AlterField(
            model_name='intentoevaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intentoevaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
