# Generated by Django 5.0.6 on 2024-06-18 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0013_remove_intentoevaluacion_fecha_intento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intento_evaluacion', to='Evaluaciones.evaluacion'),
        ),
        migrations.AlterField(
            model_name='intentoevaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intento_evaluacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
