# Generated by Django 5.0.6 on 2024-06-19 06:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0014_alter_intentoevaluacion_evaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoevaluacion',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='respuestas',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta', to='Evaluaciones.intentoevaluacion'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='respuesta',
            field=models.JSONField(default=dict),
        ),
    ]
