# Generated by Django 5.0.6 on 2024-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0015_intentoevaluacion_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestapregunta',
            name='respuesta',
            field=models.TextField(),
        ),
    ]
