# Generated by Django 5.0.6 on 2024-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0016_alter_respuestapregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoría',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
