# Generated by Django 5.0.6 on 2024-06-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_temacompletado'),
        ('Evaluaciones', '0017_pregunta_categoría'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='curso_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cursos.curso'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='rubrica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tema_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cursos.tema'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
