# Generated by Django 5.0.6 on 2024-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0018_evaluacion_curso_evaluacion_evaluacion_rubrica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='marcar_respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
