# Generated by Django 5.0.6 on 2024-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0019_pregunta_marcar_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
