# Generated by Django 5.0.6 on 2024-06-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0020_evaluacion_puntaje_maximo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
