# Generated by Django 5.0.6 on 2024-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0021_rename_categoría_pregunta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
