# Generated by Django 5.0.6 on 2024-06-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0022_evaluacion_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='aprobado',
        ),
    ]
