# Generated by Django 5.0.6 on 2024-06-20 18:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0023_remove_evaluacion_aprobado'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo_pregunta',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_svg',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto_pregunta',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
