# Generated by Django 5.0.6 on 2024-06-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0023_remove_evaluacion_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='curso_evaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='leccion_evaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='rubrica',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='tema_evaluacion',
        ),
    ]
