# Generated by Django 5.0.6 on 2024-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0025_evaluacion_curso_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto_pregunta',
            field=models.TextField(blank=True),
        ),
    ]
