# Generated by Django 5.0.6 on 2024-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0026_alter_pregunta_texto_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_svg',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
    ]
