# Generated by Django 5.0.6 on 2024-06-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0024_remove_pregunta_imagen_remove_pregunta_tipo_pregunta_and_more'),
        ('Evaluaciones', '0027_remove_pregunta_imagen_alter_pregunta_imagen_svg'),
    ]

    operations = [
    ]
