# Generated by Django 5.0.6 on 2024-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0028_merge_20240620_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Múltiple', 'Múltiple'), ('Abierta', 'Abierta'), ('Verdadero/Falso', 'Verdadero/Falso')], default='Simple', max_length=15),
        ),
    ]
