# Generated by Django 5.0.6 on 2024-06-21 05:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0029_pregunta_tipo_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_svg',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
