# Generated by Django 5.0.6 on 2024-06-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0030_alter_pregunta_imagen_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapregunta',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.opcion'),
        ),
    ]
