# Generated by Django 5.0.6 on 2024-07-25 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evaluaciones', '0002_initial'),
        ('Lecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='entregas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Versión amigable del título para URL.', max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('peso_en_calificacion_final', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('revisiones_permitidas', models.PositiveIntegerField()),
                ('peso_tareas_colaborativas', models.BooleanField(default=False)),
                ('es_opcional', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=12)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entregas', models.ManyToManyField(related_name='tareas_entregadas', through='Tareas.EntregaTarea', to=settings.AUTH_USER_MODEL)),
                ('evaluacion_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Evaluaciones.evaluacion')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Lecciones.leccion')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tarea', to='Tareas.tarea'),
        ),
    ]
