# Generated by Django 5.0.6 on 2024-07-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articulos', '0001_initial'),
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='Usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='articulos_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articuloview',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='Articulos.articulo'),
        ),
        migrations.AddField(
            model_name='articuloview',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_articulos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaarticulo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='Articulos.area'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='Articulos.categoriaarticulo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Articulos.articulo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='Articulos.articulo'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temaarticulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='Articulos.categoriaarticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='Articulos.temaarticulo'),
        ),
        migrations.AddField(
            model_name='usuarioarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_articulos', to='Articulos.articulo'),
        ),
        migrations.AddField(
            model_name='usuarioarticulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_articulos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='estudiantes',
            field=models.ManyToManyField(related_name='articulos_matriculados', through='Articulos.UsuarioArticulo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'articulo')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioarticulo',
            unique_together={('usuario', 'articulo')},
        ),
    ]
