# Generated by Django 5.0.6 on 2024-06-08 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-creado']},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='contenido_latex',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='universidad',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='usuarioarticulo',
            name='fecha_matricula',
        ),
        migrations.RemoveField(
            model_name='usuarioarticulo',
            name='leido',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Articulos.articulo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
