# Generated by Django 5.0.6 on 2024-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='portada_articulo',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_articulos/'),
        ),
    ]
