# Generated by Django 5.0.6 on 2024-06-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='evaluacion_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tema_asociado', to='Evaluaciones.evaluacion'),
        ),
    ]
