# Generated by Django 5.0.6 on 2024-07-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='evaluacion_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tema_asociado', to='Evaluaciones.evaluacion', verbose_name='Evaluación asociada'),
        ),
        migrations.AddField(
            model_name='leccion',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_tema', to='Cursos.tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='temacompletado',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_completados', to='Cursos.tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='temacompletado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_completados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('usuario', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='leccioncompletada',
            unique_together={('usuario', 'leccion')},
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('usuario', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together={('curso', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('curso', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='leccion',
            unique_together={('tema', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='temacompletado',
            unique_together={('usuario', 'tema')},
        ),
    ]
