# Generated by Django 5.0.6 on 2024-07-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
