# Generated by Django 5.0.6 on 2024-06-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_tema_evaluacion_asociada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_completados', to='Cursos.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_completados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema Completado',
                'verbose_name_plural': 'Temas Completados',
                'ordering': ['-fecha_completado'],
                'unique_together': {('usuario', 'tema')},
            },
        ),
    ]
