# Generated by Django 5.0.6 on 2024-07-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_categoria_slug_alter_curso_slug_alter_tag_slug'),
        ('Matriculas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='inscripciones',
            field=models.ManyToManyField(related_name='inscripciones_curso', to='Matriculas.inscripcion'),
        ),
    ]
