# Generated by Django 5.0.6 on 2024-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_temacompletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='portada_curso',
            field=models.ImageField(blank=True, upload_to='portadas_cursos/'),
        ),
    ]
