# Generated by Django 5.0.6 on 2024-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_curso_portada_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion_total',
            field=models.PositiveIntegerField(default=0, help_text='Duración total en minutos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='idiomas_disponibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel_satisfaccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos_tecnicos',
            field=models.TextField(blank=True, verbose_name='Requisitos técnicos'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='especialidades',
            field=models.ManyToManyField(related_name='instructores_especializados', to='Cursos.categoria'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reseña',
            name='utilidad',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='objetivos_aprendizaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='recursos_adicionales',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
