# Generated by Django 5.0.6 on 2024-07-25 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_alter_curso_inscripciones'),
        ('Matriculas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=models.ManyToManyField(related_name='cursos_inscritos', through='Matriculas.Inscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Inscritos'),
        ),
    ]
