# Generated by Django 5.0.6 on 2024-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_alter_curso_inscritos'),
        ('Matriculas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscripciones',
            field=models.ManyToManyField(related_name='inscripciones_curso', to='Matriculas.inscripcion'),
        ),
    ]
