# Generated by Django 5.0.6 on 2024-07-25 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0007_alter_curso_inscripciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscripciones',
            field=models.ManyToManyField(related_name='inscripciones_curso', to='Cursos.inscripcion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=models.ManyToManyField(related_name='cursos_inscritos', through='Cursos.Inscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Inscritos'),
        ),
    ]
