# Generated by Django 5.0.6 on 2024-07-27 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_alter_curso_inscripciones_alter_curso_inscritos'),
        ('Matriculas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscripciones',
            field=models.ManyToManyField(related_name='inscripciones_curso', to='Matriculas.inscripcion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=models.ManyToManyField(related_name='cursos_inscritos', through='Matriculas.Inscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Inscritos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='portada_curso',
            field=models.ImageField(blank=True, upload_to='Matriculas.portadas_cursos/', verbose_name='Portada del curso'),
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
