# Generated by Django 5.0.6 on 2024-06-06 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articulos', '0001_initial'),
        ('Cursos', '0001_initial'),
        ('Matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios.', regex='^[A-Za-z\\s]*$')])),
                ('apellido', models.CharField(blank=True, max_length=255)),
                ('profesion', models.CharField(blank=True, default='Estudiante', max_length=255)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?[0-9]{9,15}$')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, max_length=1024, null=True)),
                ('biografia', models.TextField(blank=True, help_text='Una breve biografía sobre ti.', max_length=5000, null=True)),
                ('twitter', models.URLField(blank=True, max_length=1024, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=1024, null=True)),
                ('github', models.URLField(blank=True, max_length=1024, null=True)),
                ('website', models.URLField(blank=True, help_text='Tu sitio web personal o portafolio.', max_length=1024, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cursos_inscritos', models.ManyToManyField(related_name='perfiles_inscritos', through='Matriculas.Inscripcion', to='Cursos.curso')),
                ('universidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='Articulos.universidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
