# Generated by Django 5.0.6 on 2024-06-06 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0002_tema_evaluacion_asociada'),
        ('Evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Versión amigable del título para URL.', unique=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicada', 'Publicada'), ('Archivada', 'Archivada')], default='Borrador', max_length=10)),
                ('tiempo_estimado', models.PositiveIntegerField(help_text='Tiempo estimado en minutos')),
                ('tiene_material', models.BooleanField(default=False)),
                ('es_demo', models.BooleanField(default=False)),
                ('tipo_leccion', models.CharField(choices=[('Video', 'Video'), ('Texto', 'Texto'), ('Seminario', 'Seminario')], default='Video', max_length=9)),
                ('contenido_texto', models.TextField(blank=True)),
                ('contenido_multimedia', models.URLField(blank=True, max_length=1024)),
                ('orden', models.PositiveIntegerField()),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación de la lección del 1 al 10', max_digits=5, null=True)),
                ('progreso_por_usuario', models.JSONField(default=dict)),
                ('eventos', models.JSONField(default=list)),
                ('feedbacks', models.JSONField(default=list)),
                ('completada_por', models.ManyToManyField(blank=True, related_name='lecciones_completadas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leccion_asociada', to='Evaluaciones.evaluacion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to=settings.AUTH_USER_MODEL)),
                ('prerrequisitos', models.ManyToManyField(blank=True, related_name='lecciones_siguientes', to='Lecciones.leccion')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='Cursos.tema')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'unique_together': {('titulo', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='Lecciones.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
                'unique_together': {('usuario', 'leccion')},
            },
        ),
    ]
