# Generated by Django 5.0.6 on 2024-07-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lecciones', '0003_leccioncompletada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leccioncompletada',
            old_name='fecha_completada',
            new_name='fecha_completado',
        ),
    ]
