# Generated by Django 5.0.6 on 2024-06-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('progreso', models.FloatField(default=0.0, verbose_name='Progreso')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('certificado_url', models.URLField(blank=True, max_length=1024)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Cursos.curso')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['fecha_inscripcion'],
            },
        ),
    ]
