# Generated by Django 5.0.6 on 2024-06-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matriculas', '0001_initial'),
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to='Usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'curso')},
        ),
    ]
