# Generated by Django 5.0.6 on 2024-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
